### ISSUE TITLE
Can cookies be added to requests?

### ISSUE THREAD

**Issue by Buzzkill-McSquare** [rswag/rswag#439] opened 2021-08-02 22:46 UTC
We're working on an authorization system that expects & verifies that a token is coming from a valid place with the use of a fingerprint cookie. All of my specs now fail because they don't have the proper cookie. Is there a way to add cookies to specs? I've seen other posts related to cookie/session authorization, but this isn't that.

**Comment by oblakeerickson** [comment] 2021-08-03 00:50
I add a `sign_in` method call in the before block of each rswag spec, so something like that can be adapted for your app

```
before do
  sign_in(user)
end
```

the `sign_in` method can be added to something like `spec/support/integration_helpers.rb` file. This helper is also used in some normal rspec tests not just rswag specs.

**Comment by Buzzkill-McSquare** [comment] 2021-08-03 19:41
I don't think that this would give me what I want. I don't need to ensure that someone is signed in before running tests, I just need to be able to provide cookies in requests. I actually don't think that it's possible to do so, since cookies are a browser-specific feature.

**Comment by jaydorsey** [comment] 2021-08-10 02:13
I'll test this tomorrow, but I think you should be able to use something similar to the strategy you'd use to send an authorization header (since a cookie is just a header attribute/setting). 

```ruby
# swagger_helper.rb
cookie: {
  description: 'cookie',
  type: :apiKey,
  name: 'cookie',
  in: :header
}
```

Your spec would set the cookie

```ruby
describe 'foo' do
  security: [cookie: []]

  response '200', 'found' do

  # fingerprint cookie goes here
  let(:cookie) { 'fingerprint_hash=whatever;other_data=true;' }
```

There might be a better way to do this without using a security scheme but I think this kind of makes sense if you're using it as some type of auth mechanism.

Edit: Here's a link to some discussion around using the [cookie as a parameter](https://github.com/rswag/rswag/issues/48#issuecomment-283254574). You'll note it also mentions the security definition pattern i noted above

**Comment by jaydorsey** [comment] 2021-08-12 21:00
Confirmed, this works fine with a request spec, with the `cookie` security definition above.

```
# spec/requests/health_spec.rb
describe 'Health' do
  path '/health' do
    get 'Get health' do
      security [cookie: []]

      tags 'Health'

      let(:cookie) { 'foo=bar;' }

      response '200', 'found' do
        run_test!
      end
    end
  end
end
```

Inside my controller action, if I `binding.pry` inside of the `index` action I can see my cookies

![image](https://user-images.githubusercontent.com/191564/129268553-407dc5d8-b41b-40bb-8cee-19a579e743ce.png)

This works as _I_ expected it to, at least (I haven't dealt with cookies in a while).

**Comment by Buzzkill-McSquare** [comment] 2021-08-12 22:24
Unfortunately that doesn't work for me, I'm already using a `security` definition; the cookie is an added layer of security.

**Comment by jaydorsey** [comment] 2021-08-13 01:52
I haven't tested this, but the docs make it seem like you can do something like `security [basic: [], cookie: []]` (or apikey instead of basic or whatever you use)

Barring that working, you might have to just do a stub of the method that does the cookie security method. e.g. `it_behaves_like 'valid cookie'` and `it_behaves_like 'invalid cookie'` as shared examples

There might be another way but those are the only ones that come to mind

**Comment by Buzzkill-McSquare** [comment] 2021-08-13 16:42
I'll keep those approaches in mind and let you know if they work.

**Comment by dim0627** [comment] 2022-06-10 00:28
I have same issue
Is there any updates?

**Comment by eboyko** [comment] 2022-07-07 16:05
Trying to add rswag into current project (openapi 3.0.1). 

1. Added security definition (I tried to set `cookie` and `header` as `in` value, same result):

```yaml
components:
  securitySchemes:
    SessionKey:
      name: token
      type: apiKey
      in: cookie
```

2. Tried to check request headers. Got an error `undefined method 'Authorization' for #<RSpec::ExampleGroups::Users::CompanyUserProfile::Get::Unauthorized>`.

```ruby
describe 'Users' do
  let(:current_user) { create(:user) }
  let(:current_session) { create(:user_session, user: current_user) }

  path '/company/user/profile' do
    get 'show' do
      security [SessionKey: []]

      response 401, 'unauthorized' do
        run_test! do
          puts request.headers.map { |header| header.to_s }
        end
      end
    end
  end
end
```

3. Defined `Authorization`:

```ruby
let(:Authorization) { "token=#{current_session.token}" }
```

Now I have very strange headers content `puts request.headers.map { |header| header.to_s }`:

```
["HTTP_AUTHORIZATION", "token=secret"]
["HTTP_COOKIE", ""]
```

Why I was forced to declare `Authorization` variable?
Why [official security scheme definition](https://swagger.io/docs/specification/authentication/cookie-authentication/) does not work?

**Comment by franzliedke** [comment] 2022-11-15 13:58
In the context of a Rails request spec, this worked for me:

```ruby
before { cookies["my_cookie"] = "my_value" }
```

**Comment by jtannas** [comment] 2022-11-27 21:43
Seems resolved; closing the issue but feel free to reopen it if there are any further problems.

**Closed as completed by jtannas** 2022-11-27 21:43 UTC

**Comment by wethu** [comment] 2023-05-26 01:37
> Why I was forced to declare `Authorization` variable?

Hey mate, 

I've run into this myself, and this relates to how the mappings for the `let` magic is working. Can see here: https://github.com/rswag/rswag/blob/master/rswag-specs/lib/rswag/specs/request_factory.rb#L46

The mapping is calculated with **symbol** keys, and **symbol** values.

In my experience I was using a `yaml` file to store our swagger document. 

I solved this by both calling `#deep_symbolize_keys` on my `YAML.load` and then ensuring the values are symbols in the document itself:

```yaml
  securitySchemes:
    CookieAuth:
      type: :apiKey
      in: :header
      name: :cookie
```

Ensuring that both the key and value are both symbols, otherwise, the check will fallback and require the `Authorization` variable.

Hope this helps someone, its certainly confusing that it was working for some and not others, and I believe it was all down to the chance of which value types they happened to have configured.
