### ISSUE TITLE
Update swagger-ui version to at least 4.1.3

### ISSUE THREAD

**Issue by stjshi** [rswag/rswag#485] opened 2022-02-03 20:30 UTC
Hey all! Are there plans to update the swagger-ui version?

```
SwaggerUI supports displaying remote OpenAPI definitions through the ?url parameter. This enables robust demonstration capabilities on sites like petstore.swagger.io, editor.swagger.io, and similar sites, where users often want to see what their OpenAPI definitions would look like rendered.
However, this functionality may pose a risk for users who host their own SwaggerUI instances. In particular, including remote OpenAPI definitions opens a vector for phishing attacks by abusing the trusted names/domains of self-hosted instances.
Resolution:
We've made the decision to disable query parameters (#4872) by default starting with SwaggerUI version 4.1.3. Please update to this version when it becomes available (ETA: 2021 December). Users will still be able to be re-enable the options at their discretion. We'll continue to enable query parameters on the Swagger demo sites.
```
[Advisory page](https://github.com/swagger-api/swagger-ui/commit/01a3e55960f864a0acf6a8d06e5ddaf6776a7f76)

**Comment by jtannas** [comment] 2022-02-10 04:15
Kind of?
The gem has fallen behind over the last year so we just brought on a bunch more people to help. See here for the story: https://github.com/rswag/rswag/issues/468

We obviously want to keep up with all the latest & greatest tools, but right now we have a lot of catch up to do and don't know when we'll get around to that particular version bump.
If you or anyone else you know would like to help out we'd really appreciate it 🙇

**Comment by romanblanco** [comment] 2022-09-28 06:57
@jtannas I think this can be closed as duplicate of https://github.com/rswag/rswag/issues/534#issuecomment-1259124187

**Comment by jtannas** [comment] 2022-09-28 17:19
Agreed - looks like this is done now: https://github.com/rswag/rswag/blob/master/rswag-ui/package.json#L6

**Closed as completed by jtannas** 2022-09-28 17:19 UTC
Labels: dependencies
