### ISSUE TITLE
Using parameter with name :date / 'date'

### ISSUE THREAD

**Issue by paulomcnally** [rswag/rswag#459] opened 2021-11-03 18:02 UTC
`parameter name: :date, in: :query, type: :string, required: true`

```
api/v2/calendars
  /api/v2/calendars/days
    get
      successful
        returns a 200 response (FAILED - 1)
      unauthorized request
/Users/mcnally/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:342: [BUG] vm_call_cfunc - cfp consistency error
ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-darwin20]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.
```

**Comment by jtannas** [comment] 2022-02-09 02:23
This looks like a crash from Ruby, specifically Ruby v2.3.6. That version went EOL on March 31, 2019.
https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/

Are you able to reproduce the issue on a current version of Ruby?

**Comment by jtannas** [comment] 2022-02-16 07:38
Closing this ticket since it appears to be due to running on an unsupported version of Ruby.
If you manage to reproduce this on a supported version of Ruby please open another ticket and we'll be happy to help 🙂

**Closed as completed by jtannas** 2022-02-16 07:38 UTC
