### ISSUE TITLE
[BUG] FormData not rendering

### ISSUE THREAD

**Issue by dominicsanto** [rswag/rswag#504] opened 2022-03-14 15:11 UTC
## Describe the bug
I am trying to render a multi-part form in order to add parameters to my post request.

## Steps to Test or Reproduce
I have the following configuration:

``` 
      consumes 'multipart/form-data'
      produces 'application/json'
      parameter name: :thing, in: :formData, schema: {
        type: :object,
        properties: {
          thing: {
            type: :object,
            properties: {
              name:                 { type: :string, default: "My Company" },
              main_logo:         { type: :file },
              images:               { type: :array,
                items: {
                  type: :file
                }
              }
            }
          }
        },
        required: :thing
      }
```

## Expected behavior
I expect to see a form where I can add my params and upload files that need to be submitted

## Rswag Version
2.5

## Relates to which version of OAS (Open API Specification)
- [x] OAS3.1

**Comment by romanblanco** [comment] 2023-03-19 19:43
@dominicsanto Have you tried following the example in [test-app](https://github.com/rswag/rswag/commit/b1619837#diff-0e56ca46a4d0b9e006edbdbc4daa529ca9a17724ac7b923a47428117c2db6b02R98)?

**Comment by romanblanco** [comment] 2023-03-19 19:47
@dominicsanto this issue seems to be a duplicate of https://github.com/rswag/rswag/pull/451. Can you confirm?

**Closed as completed** 2024-11-30 17:06 UTC
Labels: duplicate, help wanted, question, wontfix

**Comment by pboling** [comment] 2024-12-12 03:07
Stale bot is destroying this repo @romanblanco
