### ISSUE TITLE
[BUG] Autosaving response examples still does not work

### ISSUE THREAD

**Issue by cenotaph** [rswag/rswag#511] opened 2022-04-28 12:28 UTC
I have been an rswag fan for some time but have always struggled to consistently capture examples automatically, both request and response types. Documentation for this has changed over time with various versions, but as of the latest release (2.5.1), the documentation states "However, auto generated example responses are now enabled by default in rswag."

It is not, however; immediately following this are instructions on how to enable auto-generated example responses with an after callback in each test (so I guess it is NOT enabled by default), but this does not work either. The code example (in the README section 'Enable auto generation examples from responses') is not valid Ruby and is missing commas and has an extra closing brace; even when corrected to run, my resulting docs are sadly example-less.

At least on Rails 6.0.3.6 and rswag 2.5.1, I cannot for the life of me figure out how to capture response examples for OpenAPI 3.0.1. This is I believe to be the most useful feature of this tool, but it's been a struggle to have the behaviour be consistent over various releases. The archive of Issues are filled with various patches and overrides to try to do this, complicated somewhat by OpenAPI 3.0 changing the location of the examples, and it's all very confusing.

Can clear documentation be provided on how to auto capture response (and ideally, also request) examples? I really love rswag and wish I could contribute more than just complaining about bugs but I am very grateful for all of the efforts here.

**Comment by asavageiv** [comment] 2022-05-03 22:06
I was able to work around this by setting the env variable `SWAGGER_DRY_RUN=0`

**Comment by asavageiv** [comment] 2022-05-03 22:12
Just kidding. That gets the tests to run, but does not auto-generate the examples

**Comment by asavageiv** [comment] 2022-05-03 22:26
I think this is a dupe of #337

**Comment by lucasocon** [comment] 2022-05-19 17:05
If you want to generate documentation with examples you can run:
`rake rswag:specs:swaggerize SWAGGER_DRY_RUN=0`

If you want to generate examples without passing the env variable you can add this to your `config/environments/test.rb`

```
RSpec.configure do |config|
  config.swagger_dry_run = false
end
```

Don't forget to add these lines to your specs to include examples:

```
after do |example|
  # No metadata to generate for empty responses like 201 and 204.
  next unless respond_to?(:response) && response&.body.present?

  # Generate the examples for the API docs.
  example.metadata[:response][:content] = {
    'application/json' => {
      example: JSON.parse(response.body, symbolize_names: true)
    }
  }
end
```

Link to doc: https://github.com/rswag/rswag#enable-auto-generation-examples-from-responses

**Comment by jiz4oh** [comment] 2022-08-26 10:05
`SWAGGER_DRY_RUN=0 RAILS_ENV=test rails rswag:specs:swaggerize` works for me.
`config.swagger_dry_run = false` is not

**Comment by akaJSaunders** [comment] 2022-11-12 09:53
Just wanted to contribute to the conversation by saying that I was struggling with the same issues for a few weeks, and then yesterday after updating the rswag gems to the latest version, it started working fine. Hopefully, this helps some of you out there 🥲

**Closed as completed** 2023-03-19 09:27 UTC
Labels: bug, duplicate
