### ISSUE TITLE
Issue with Devise endpoint on an API

### ISSUE THREAD

**Issue by Kutomore** [rswag/rswag#259] opened 2019-12-08 15:15 UTC
While trying to test and document an endpoint on my API I have come across an issue. The documentation works flawlessly. But whenever I try to test the `/signup` endpoint(just run the test that is generated with the documentation) I get an error related to JWT and warden:

```
1) Auth API /signup post Auth Created returns a 200 response
     Failure/Error: ref = request.content_mime_type.ref
     
     NoMethodError:
       undefined method `ref' for nil:NilClass
       Did you mean?  def
```

The test is pretty simple:

```
response '200', 'Auth Created' do
        let(:auth) { FactoryBot.attributes_for(:auth).merge(user_attributes: FactoryBot.attributes_for(:user)) }
        schema type: :object,
               properties: {
                 data: {
                   '$ref': '#/definitions/auth_object'
                 }
               }
        run_test!
      end
```
I make the hash that will be sent to the endpoint, and thats it, the schema also seems to be ok since I can execute the request using the docs with 0 issue. Using postman also gives me no trouble, only when I try to run this spec I get this error, any idea what it might be?

**Comment by BookOfGreg** [comment] 2019-12-09 20:45
You're the second person to mention this recently so I'll try whip up an OAuth/Devise/Doorkeeper example app see if there's something going on here that I've missed until now. :)

**Comment by Kutomore** [comment] 2019-12-09 22:10
If you find it relevant, my implementation followed [this article](https://medium.com/@mazik.wyry/rails-5-api-jwt-setup-in-minutes-using-devise-71670fd4ed03). Anyway, I'll check the other issue, maybe I'll find something aswell.

**Comment by ktaras** [comment] 2019-12-18 21:43
Have the same issue with rails (6.0.1, api mode) + devise_token_auth (1.1.3) + rswag (2.2.0)

**Comment by BookOfGreg** [comment] 2022-02-11 20:46
Duplicate of #258 Sorry it's been taking so long to get to these. We've only recently been able to get new people to volunteer to help :pray:

**Closed as completed by BookOfGreg** 2022-02-11 20:46 UTC
Labels: duplicate, wontfix
