### ISSUE TITLE
API versioning in #path

### ISSUE THREAD

**Issue by dominikdarnel** [rswag/rswag#379] opened 2020-11-13 14:30 UTC
Hey!

I would like to version my API through RSwag.
I would like to omit the api version prefix from each path for better readability of the Swagger Documentation.
Can I do that?
So I would like to see this:

```ruby
path '/tasks' do
  ...
end
```

Instead of this:

```ruby
path '/api/v1/tasks' do
  ...
end
```

But when I try the former it throws the following error:

```ruby
   No route matches [GET] "/tasks"
```

What can I do about that?

**Comment by tarassov** [comment] 2021-01-03 22:28
You can add basePath: "/api/v1/" to your swagger_helper file. 
But after that your yaml file  will not be valid. But it works.
it was discussed here: 
https://github.com/rswag/rswag/issues/318

**Comment by oblakeerickson** [comment] 2021-02-10 15:45
Closing this as it is a duplicate of #318 ^

**Closed as completed by oblakeerickson** 2021-02-10 15:45 UTC
Labels: duplicate
